version: '2.2'
services:
  client:
    build:
      context: ../../../
      dockerfile: docker/dev/client/Dockerfile
    volumes:
      - ../../../client:/go/src/client
    env_file:
      - ../../../client/.env
networks:
  default:
    external:
      name: mole-local-network
