version: '2.2'
services:
  client:
    build:
      context: ../../../
      dockerfile: docker/dev/client/Dockerfile
    volumes:
      - ../../../client:/go/src/client
    ports:
      - '8080:8080'
    env_file:
      - ../../../client/.env
    environment:
      PORT: 8080
networks:
  default:
    external:
      name: mole-local-network
